[package]
name = "aleph-node"
version = "0.4.0"
authors = ["Cardinal Cryptography"]
description = "Aleph node binary"
edition = "2021"
license = "Apache 2.0"
build = "build.rs"
homepage = "https://alephzero.org"
repository = "https://github.com/aleph-zero-foundation/aleph-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "aleph-node"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
log = "0.4"
serde = "1.0"
serde_json = "1.0"
futures = "0.3"
hex = "0.4"
hex-literal = "0.3"
libp2p = "0.40"

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
sp-application-crypto = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-block-builder = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-cli = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation", features = ["wasmtime"]}
sp-core = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-executor = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation", features = ["wasmtime"]}
sc-service = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation", features = ["wasmtime"]}
sc-telemetry = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-keystore = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-keystore = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-inherents = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-basic-authorship = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-network = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-transaction-pool = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-transaction-pool = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-transaction-pool-api = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-consensus-aura = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-consensus-aura = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-consensus = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-consensus = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-client-api = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-runtime = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-timestamp = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation" }
pallet-staking = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation" }

aleph-runtime = { path = "../runtime"}
finality-aleph = { path = "../../finality-aleph"}
aleph-primitives = { package = "primitives", path = "../../primitives"}

# These dependencies are used for the node's RPCs
jsonrpc-core = "18.0"
sc-rpc = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-api = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sc-rpc-api = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-blockchain = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
sp-block-builder = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
substrate-frame-rpc-system = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}
pallet-transaction-payment-rpc = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "turn-off-reputation"}

[features]
default = []
short_session = [
    "aleph-runtime/short_session",
    "aleph-primitives/short_session"
]